// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqWSDOXy9SIA8ecx-xsWbpi-sIo3VS63w',
    appId: '1:849892312036:web:71adb4c67099d8a467fdf1',
    messagingSenderId: '849892312036',
    projectId: 'first-project-856aa',
    authDomain: 'first-project-856aa.firebaseapp.com',
    storageBucket: 'first-project-856aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEmO7yNFA-Oh3na66sYHaP89pusPLELr0',
    appId: '1:849892312036:android:07ed8c81c8af875f67fdf1',
    messagingSenderId: '849892312036',
    projectId: 'first-project-856aa',
    storageBucket: 'first-project-856aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfB9uMalWTKTlG_VTLkR_i7Dt2W_58fiM',
    appId: '1:849892312036:ios:26152e87fb9b3dcd67fdf1',
    messagingSenderId: '849892312036',
    projectId: 'first-project-856aa',
    storageBucket: 'first-project-856aa.firebasestorage.app',
    iosBundleId: 'com.example.coffeeCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfB9uMalWTKTlG_VTLkR_i7Dt2W_58fiM',
    appId: '1:849892312036:ios:26152e87fb9b3dcd67fdf1',
    messagingSenderId: '849892312036',
    projectId: 'first-project-856aa',
    storageBucket: 'first-project-856aa.firebasestorage.app',
    iosBundleId: 'com.example.coffeeCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqWSDOXy9SIA8ecx-xsWbpi-sIo3VS63w',
    appId: '1:849892312036:web:23e579a357e73b7767fdf1',
    messagingSenderId: '849892312036',
    projectId: 'first-project-856aa',
    authDomain: 'first-project-856aa.firebaseapp.com',
    storageBucket: 'first-project-856aa.firebasestorage.app',
  );
}
